# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcGraphEvaluator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18GrpcGraphEvaluator.proto\x12\x12GrpcGraphEvaluator\x1a\x19google/protobuf/any.proto\"(\n\x14InputEntryDescriptor\x12\x10\n\x08streamId\x18\x01 \x01(\t\")\n\x15OutputEntryDescriptor\x12\x10\n\x08streamId\x18\x01 \x01(\t\"\xa8\x01\n\x15GraphEvaluatorMessage\x12\x0f\n\x07graphId\x18\x01 \x01(\t\x12=\n\x0bgraphInputs\x18\x02 \x03(\x0b\x32(.GrpcGraphEvaluator.InputEntryDescriptor\x12?\n\x0cgraphOutputs\x18\x03 \x03(\x0b\x32).GrpcGraphEvaluator.OutputEntryDescriptor\"R\n\x13SelectionDefinition\x12\x11\n\tinterface\x18\x01 \x01(\t\x12(\n\nparameters\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\"L\n\x0eNodeDefinition\x12:\n\tselection\x18\x01 \x01(\x0b\x32\'.GrpcGraphEvaluator.SelectionDefinition\"7\n\x0e\x45\x64geDefinition\x12\x0c\n\x04\x66rom\x18\x01 \x01(\t\x12\x0b\n\x03via\x18\x02 \x03(\t\x12\n\n\x02to\x18\x03 \x01(\t\"\xd5\x01\n\x0fGraphDefinition\x12=\n\x05nodes\x18\x01 \x03(\x0b\x32..GrpcGraphEvaluator.GraphDefinition.NodesEntry\x12\x31\n\x05\x65\x64ges\x18\x02 \x03(\x0b\x32\".GrpcGraphEvaluator.EdgeDefinition\x1aP\n\nNodesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x31\n\x05value\x18\x02 \x01(\x0b\x32\".GrpcGraphEvaluator.NodeDefinition:\x02\x38\x01\"W\n\x0cInputRequest\x12\x0f\n\x07graphId\x18\x01 \x01(\t\x12\x10\n\x08streamId\x18\x02 \x01(\t\x12$\n\x06values\x18\x03 \x03(\x0b\x32\x14.google.protobuf.Any\"2\n\rOutputRequest\x12\x0f\n\x07graphId\x18\x01 \x01(\t\x12\x10\n\x08streamId\x18\x02 \x01(\t\"\r\n\x0bInputResult2\x87\x02\n\x0eGraphEvaluator\x12^\n\x08\x45valuate\x12#.GrpcGraphEvaluator.GraphDefinition\x1a).GrpcGraphEvaluator.GraphEvaluatorMessage\"\x00\x30\x01\x12N\n\x05Input\x12 .GrpcGraphEvaluator.InputRequest\x1a\x1f.GrpcGraphEvaluator.InputResult\"\x00(\x01\x12\x45\n\x06Output\x12!.GrpcGraphEvaluator.OutputRequest\x1a\x14.google.protobuf.Any\"\x00\x30\x01\x42\"\xaa\x02\x1fTdip.Qapio.Services.Grpc.Serverb\x06proto3')



_INPUTENTRYDESCRIPTOR = DESCRIPTOR.message_types_by_name['InputEntryDescriptor']
_OUTPUTENTRYDESCRIPTOR = DESCRIPTOR.message_types_by_name['OutputEntryDescriptor']
_GRAPHEVALUATORMESSAGE = DESCRIPTOR.message_types_by_name['GraphEvaluatorMessage']
_SELECTIONDEFINITION = DESCRIPTOR.message_types_by_name['SelectionDefinition']
_NODEDEFINITION = DESCRIPTOR.message_types_by_name['NodeDefinition']
_EDGEDEFINITION = DESCRIPTOR.message_types_by_name['EdgeDefinition']
_GRAPHDEFINITION = DESCRIPTOR.message_types_by_name['GraphDefinition']
_GRAPHDEFINITION_NODESENTRY = _GRAPHDEFINITION.nested_types_by_name['NodesEntry']
_INPUTREQUEST = DESCRIPTOR.message_types_by_name['InputRequest']
_OUTPUTREQUEST = DESCRIPTOR.message_types_by_name['OutputRequest']
_INPUTRESULT = DESCRIPTOR.message_types_by_name['InputResult']
InputEntryDescriptor = _reflection.GeneratedProtocolMessageType('InputEntryDescriptor', (_message.Message,), {
  'DESCRIPTOR' : _INPUTENTRYDESCRIPTOR,
  '__module__' : 'GrpcGraphEvaluator_pb2'
  # @@protoc_insertion_point(class_scope:GrpcGraphEvaluator.InputEntryDescriptor)
  })
_sym_db.RegisterMessage(InputEntryDescriptor)

OutputEntryDescriptor = _reflection.GeneratedProtocolMessageType('OutputEntryDescriptor', (_message.Message,), {
  'DESCRIPTOR' : _OUTPUTENTRYDESCRIPTOR,
  '__module__' : 'GrpcGraphEvaluator_pb2'
  # @@protoc_insertion_point(class_scope:GrpcGraphEvaluator.OutputEntryDescriptor)
  })
_sym_db.RegisterMessage(OutputEntryDescriptor)

GraphEvaluatorMessage = _reflection.GeneratedProtocolMessageType('GraphEvaluatorMessage', (_message.Message,), {
  'DESCRIPTOR' : _GRAPHEVALUATORMESSAGE,
  '__module__' : 'GrpcGraphEvaluator_pb2'
  # @@protoc_insertion_point(class_scope:GrpcGraphEvaluator.GraphEvaluatorMessage)
  })
_sym_db.RegisterMessage(GraphEvaluatorMessage)

SelectionDefinition = _reflection.GeneratedProtocolMessageType('SelectionDefinition', (_message.Message,), {
  'DESCRIPTOR' : _SELECTIONDEFINITION,
  '__module__' : 'GrpcGraphEvaluator_pb2'
  # @@protoc_insertion_point(class_scope:GrpcGraphEvaluator.SelectionDefinition)
  })
_sym_db.RegisterMessage(SelectionDefinition)

NodeDefinition = _reflection.GeneratedProtocolMessageType('NodeDefinition', (_message.Message,), {
  'DESCRIPTOR' : _NODEDEFINITION,
  '__module__' : 'GrpcGraphEvaluator_pb2'
  # @@protoc_insertion_point(class_scope:GrpcGraphEvaluator.NodeDefinition)
  })
_sym_db.RegisterMessage(NodeDefinition)

EdgeDefinition = _reflection.GeneratedProtocolMessageType('EdgeDefinition', (_message.Message,), {
  'DESCRIPTOR' : _EDGEDEFINITION,
  '__module__' : 'GrpcGraphEvaluator_pb2'
  # @@protoc_insertion_point(class_scope:GrpcGraphEvaluator.EdgeDefinition)
  })
_sym_db.RegisterMessage(EdgeDefinition)

GraphDefinition = _reflection.GeneratedProtocolMessageType('GraphDefinition', (_message.Message,), {

  'NodesEntry' : _reflection.GeneratedProtocolMessageType('NodesEntry', (_message.Message,), {
    'DESCRIPTOR' : _GRAPHDEFINITION_NODESENTRY,
    '__module__' : 'GrpcGraphEvaluator_pb2'
    # @@protoc_insertion_point(class_scope:GrpcGraphEvaluator.GraphDefinition.NodesEntry)
    })
  ,
  'DESCRIPTOR' : _GRAPHDEFINITION,
  '__module__' : 'GrpcGraphEvaluator_pb2'
  # @@protoc_insertion_point(class_scope:GrpcGraphEvaluator.GraphDefinition)
  })
_sym_db.RegisterMessage(GraphDefinition)
_sym_db.RegisterMessage(GraphDefinition.NodesEntry)

InputRequest = _reflection.GeneratedProtocolMessageType('InputRequest', (_message.Message,), {
  'DESCRIPTOR' : _INPUTREQUEST,
  '__module__' : 'GrpcGraphEvaluator_pb2'
  # @@protoc_insertion_point(class_scope:GrpcGraphEvaluator.InputRequest)
  })
_sym_db.RegisterMessage(InputRequest)

OutputRequest = _reflection.GeneratedProtocolMessageType('OutputRequest', (_message.Message,), {
  'DESCRIPTOR' : _OUTPUTREQUEST,
  '__module__' : 'GrpcGraphEvaluator_pb2'
  # @@protoc_insertion_point(class_scope:GrpcGraphEvaluator.OutputRequest)
  })
_sym_db.RegisterMessage(OutputRequest)

InputResult = _reflection.GeneratedProtocolMessageType('InputResult', (_message.Message,), {
  'DESCRIPTOR' : _INPUTRESULT,
  '__module__' : 'GrpcGraphEvaluator_pb2'
  # @@protoc_insertion_point(class_scope:GrpcGraphEvaluator.InputResult)
  })
_sym_db.RegisterMessage(InputResult)

_GRAPHEVALUATOR = DESCRIPTOR.services_by_name['GraphEvaluator']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\037Tdip.Qapio.Services.Grpc.Server'
  _GRAPHDEFINITION_NODESENTRY._options = None
  _GRAPHDEFINITION_NODESENTRY._serialized_options = b'8\001'
  _INPUTENTRYDESCRIPTOR._serialized_start=75
  _INPUTENTRYDESCRIPTOR._serialized_end=115
  _OUTPUTENTRYDESCRIPTOR._serialized_start=117
  _OUTPUTENTRYDESCRIPTOR._serialized_end=158
  _GRAPHEVALUATORMESSAGE._serialized_start=161
  _GRAPHEVALUATORMESSAGE._serialized_end=329
  _SELECTIONDEFINITION._serialized_start=331
  _SELECTIONDEFINITION._serialized_end=413
  _NODEDEFINITION._serialized_start=415
  _NODEDEFINITION._serialized_end=491
  _EDGEDEFINITION._serialized_start=493
  _EDGEDEFINITION._serialized_end=548
  _GRAPHDEFINITION._serialized_start=551
  _GRAPHDEFINITION._serialized_end=764
  _GRAPHDEFINITION_NODESENTRY._serialized_start=684
  _GRAPHDEFINITION_NODESENTRY._serialized_end=764
  _INPUTREQUEST._serialized_start=766
  _INPUTREQUEST._serialized_end=853
  _OUTPUTREQUEST._serialized_start=855
  _OUTPUTREQUEST._serialized_end=905
  _INPUTRESULT._serialized_start=907
  _INPUTRESULT._serialized_end=920
  _GRAPHEVALUATOR._serialized_start=923
  _GRAPHEVALUATOR._serialized_end=1186
# @@protoc_insertion_point(module_scope)
