# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcGraphEvaluator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='GrpcGraphEvaluator.proto',
  package='GrpcGraphEvaluator',
  syntax='proto3',
  serialized_options=b'\252\002\034Tdip.Qapio.Services.Web.Grpc',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18GrpcGraphEvaluator.proto\x12\x12GrpcGraphEvaluator\x1a\x19google/protobuf/any.proto\"(\n\x14InputEntryDescriptor\x12\x10\n\x08streamId\x18\x01 \x01(\t\")\n\x15OutputEntryDescriptor\x12\x10\n\x08streamId\x18\x01 \x01(\t\"\xa8\x01\n\x15GraphEvaluatorMessage\x12\x0f\n\x07graphId\x18\x01 \x01(\t\x12=\n\x0bgraphInputs\x18\x02 \x03(\x0b\x32(.GrpcGraphEvaluator.InputEntryDescriptor\x12?\n\x0cgraphOutputs\x18\x03 \x03(\x0b\x32).GrpcGraphEvaluator.OutputEntryDescriptor\"R\n\x13SelectionDefinition\x12\x11\n\tinterface\x18\x01 \x01(\t\x12(\n\nparameters\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\"L\n\x0eNodeDefinition\x12:\n\tselection\x18\x01 \x01(\x0b\x32\'.GrpcGraphEvaluator.SelectionDefinition\"7\n\x0e\x45\x64geDefinition\x12\x0c\n\x04\x66rom\x18\x01 \x01(\t\x12\x0b\n\x03via\x18\x02 \x03(\t\x12\n\n\x02to\x18\x03 \x01(\t\"\xd5\x01\n\x0fGraphDefinition\x12=\n\x05nodes\x18\x01 \x03(\x0b\x32..GrpcGraphEvaluator.GraphDefinition.NodesEntry\x12\x31\n\x05\x65\x64ges\x18\x02 \x03(\x0b\x32\".GrpcGraphEvaluator.EdgeDefinition\x1aP\n\nNodesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x31\n\x05value\x18\x02 \x01(\x0b\x32\".GrpcGraphEvaluator.NodeDefinition:\x02\x38\x01\"W\n\x0cInputRequest\x12\x0f\n\x07graphId\x18\x01 \x01(\t\x12\x10\n\x08streamId\x18\x02 \x01(\t\x12$\n\x06values\x18\x03 \x03(\x0b\x32\x14.google.protobuf.Any\"2\n\rOutputRequest\x12\x0f\n\x07graphId\x18\x01 \x01(\t\x12\x10\n\x08streamId\x18\x02 \x01(\t\"\r\n\x0bInputResult2\x87\x02\n\x0eGraphEvaluator\x12^\n\x08\x45valuate\x12#.GrpcGraphEvaluator.GraphDefinition\x1a).GrpcGraphEvaluator.GraphEvaluatorMessage\"\x00\x30\x01\x12N\n\x05Input\x12 .GrpcGraphEvaluator.InputRequest\x1a\x1f.GrpcGraphEvaluator.InputResult\"\x00(\x01\x12\x45\n\x06Output\x12!.GrpcGraphEvaluator.OutputRequest\x1a\x14.google.protobuf.Any\"\x00\x30\x01\x42\x1f\xaa\x02\x1cTdip.Qapio.Services.Web.Grpcb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])




_INPUTENTRYDESCRIPTOR = _descriptor.Descriptor(
  name='InputEntryDescriptor',
  full_name='GrpcGraphEvaluator.InputEntryDescriptor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='streamId', full_name='GrpcGraphEvaluator.InputEntryDescriptor.streamId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=115,
)


_OUTPUTENTRYDESCRIPTOR = _descriptor.Descriptor(
  name='OutputEntryDescriptor',
  full_name='GrpcGraphEvaluator.OutputEntryDescriptor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='streamId', full_name='GrpcGraphEvaluator.OutputEntryDescriptor.streamId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=158,
)


_GRAPHEVALUATORMESSAGE = _descriptor.Descriptor(
  name='GraphEvaluatorMessage',
  full_name='GrpcGraphEvaluator.GraphEvaluatorMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='graphId', full_name='GrpcGraphEvaluator.GraphEvaluatorMessage.graphId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='graphInputs', full_name='GrpcGraphEvaluator.GraphEvaluatorMessage.graphInputs', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='graphOutputs', full_name='GrpcGraphEvaluator.GraphEvaluatorMessage.graphOutputs', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=329,
)


_SELECTIONDEFINITION = _descriptor.Descriptor(
  name='SelectionDefinition',
  full_name='GrpcGraphEvaluator.SelectionDefinition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='interface', full_name='GrpcGraphEvaluator.SelectionDefinition.interface', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='parameters', full_name='GrpcGraphEvaluator.SelectionDefinition.parameters', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=331,
  serialized_end=413,
)


_NODEDEFINITION = _descriptor.Descriptor(
  name='NodeDefinition',
  full_name='GrpcGraphEvaluator.NodeDefinition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='selection', full_name='GrpcGraphEvaluator.NodeDefinition.selection', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=415,
  serialized_end=491,
)


_EDGEDEFINITION = _descriptor.Descriptor(
  name='EdgeDefinition',
  full_name='GrpcGraphEvaluator.EdgeDefinition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='from', full_name='GrpcGraphEvaluator.EdgeDefinition.from', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='via', full_name='GrpcGraphEvaluator.EdgeDefinition.via', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='to', full_name='GrpcGraphEvaluator.EdgeDefinition.to', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=493,
  serialized_end=548,
)


_GRAPHDEFINITION_NODESENTRY = _descriptor.Descriptor(
  name='NodesEntry',
  full_name='GrpcGraphEvaluator.GraphDefinition.NodesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='GrpcGraphEvaluator.GraphDefinition.NodesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='GrpcGraphEvaluator.GraphDefinition.NodesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=684,
  serialized_end=764,
)

_GRAPHDEFINITION = _descriptor.Descriptor(
  name='GraphDefinition',
  full_name='GrpcGraphEvaluator.GraphDefinition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodes', full_name='GrpcGraphEvaluator.GraphDefinition.nodes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='edges', full_name='GrpcGraphEvaluator.GraphDefinition.edges', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_GRAPHDEFINITION_NODESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=551,
  serialized_end=764,
)


_INPUTREQUEST = _descriptor.Descriptor(
  name='InputRequest',
  full_name='GrpcGraphEvaluator.InputRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='graphId', full_name='GrpcGraphEvaluator.InputRequest.graphId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='streamId', full_name='GrpcGraphEvaluator.InputRequest.streamId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='values', full_name='GrpcGraphEvaluator.InputRequest.values', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=766,
  serialized_end=853,
)


_OUTPUTREQUEST = _descriptor.Descriptor(
  name='OutputRequest',
  full_name='GrpcGraphEvaluator.OutputRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='graphId', full_name='GrpcGraphEvaluator.OutputRequest.graphId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='streamId', full_name='GrpcGraphEvaluator.OutputRequest.streamId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=855,
  serialized_end=905,
)


_INPUTRESULT = _descriptor.Descriptor(
  name='InputResult',
  full_name='GrpcGraphEvaluator.InputResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=907,
  serialized_end=920,
)

_GRAPHEVALUATORMESSAGE.fields_by_name['graphInputs'].message_type = _INPUTENTRYDESCRIPTOR
_GRAPHEVALUATORMESSAGE.fields_by_name['graphOutputs'].message_type = _OUTPUTENTRYDESCRIPTOR
_SELECTIONDEFINITION.fields_by_name['parameters'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_NODEDEFINITION.fields_by_name['selection'].message_type = _SELECTIONDEFINITION
_GRAPHDEFINITION_NODESENTRY.fields_by_name['value'].message_type = _NODEDEFINITION
_GRAPHDEFINITION_NODESENTRY.containing_type = _GRAPHDEFINITION
_GRAPHDEFINITION.fields_by_name['nodes'].message_type = _GRAPHDEFINITION_NODESENTRY
_GRAPHDEFINITION.fields_by_name['edges'].message_type = _EDGEDEFINITION
_INPUTREQUEST.fields_by_name['values'].message_type = google_dot_protobuf_dot_any__pb2._ANY
DESCRIPTOR.message_types_by_name['InputEntryDescriptor'] = _INPUTENTRYDESCRIPTOR
DESCRIPTOR.message_types_by_name['OutputEntryDescriptor'] = _OUTPUTENTRYDESCRIPTOR
DESCRIPTOR.message_types_by_name['GraphEvaluatorMessage'] = _GRAPHEVALUATORMESSAGE
DESCRIPTOR.message_types_by_name['SelectionDefinition'] = _SELECTIONDEFINITION
DESCRIPTOR.message_types_by_name['NodeDefinition'] = _NODEDEFINITION
DESCRIPTOR.message_types_by_name['EdgeDefinition'] = _EDGEDEFINITION
DESCRIPTOR.message_types_by_name['GraphDefinition'] = _GRAPHDEFINITION
DESCRIPTOR.message_types_by_name['InputRequest'] = _INPUTREQUEST
DESCRIPTOR.message_types_by_name['OutputRequest'] = _OUTPUTREQUEST
DESCRIPTOR.message_types_by_name['InputResult'] = _INPUTRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InputEntryDescriptor = _reflection.GeneratedProtocolMessageType('InputEntryDescriptor', (_message.Message,), {
  'DESCRIPTOR' : _INPUTENTRYDESCRIPTOR,
  '__module__' : 'GrpcGraphEvaluator_pb2'
  # @@protoc_insertion_point(class_scope:GrpcGraphEvaluator.InputEntryDescriptor)
  })
_sym_db.RegisterMessage(InputEntryDescriptor)

OutputEntryDescriptor = _reflection.GeneratedProtocolMessageType('OutputEntryDescriptor', (_message.Message,), {
  'DESCRIPTOR' : _OUTPUTENTRYDESCRIPTOR,
  '__module__' : 'GrpcGraphEvaluator_pb2'
  # @@protoc_insertion_point(class_scope:GrpcGraphEvaluator.OutputEntryDescriptor)
  })
_sym_db.RegisterMessage(OutputEntryDescriptor)

GraphEvaluatorMessage = _reflection.GeneratedProtocolMessageType('GraphEvaluatorMessage', (_message.Message,), {
  'DESCRIPTOR' : _GRAPHEVALUATORMESSAGE,
  '__module__' : 'GrpcGraphEvaluator_pb2'
  # @@protoc_insertion_point(class_scope:GrpcGraphEvaluator.GraphEvaluatorMessage)
  })
_sym_db.RegisterMessage(GraphEvaluatorMessage)

SelectionDefinition = _reflection.GeneratedProtocolMessageType('SelectionDefinition', (_message.Message,), {
  'DESCRIPTOR' : _SELECTIONDEFINITION,
  '__module__' : 'GrpcGraphEvaluator_pb2'
  # @@protoc_insertion_point(class_scope:GrpcGraphEvaluator.SelectionDefinition)
  })
_sym_db.RegisterMessage(SelectionDefinition)

NodeDefinition = _reflection.GeneratedProtocolMessageType('NodeDefinition', (_message.Message,), {
  'DESCRIPTOR' : _NODEDEFINITION,
  '__module__' : 'GrpcGraphEvaluator_pb2'
  # @@protoc_insertion_point(class_scope:GrpcGraphEvaluator.NodeDefinition)
  })
_sym_db.RegisterMessage(NodeDefinition)

EdgeDefinition = _reflection.GeneratedProtocolMessageType('EdgeDefinition', (_message.Message,), {
  'DESCRIPTOR' : _EDGEDEFINITION,
  '__module__' : 'GrpcGraphEvaluator_pb2'
  # @@protoc_insertion_point(class_scope:GrpcGraphEvaluator.EdgeDefinition)
  })
_sym_db.RegisterMessage(EdgeDefinition)

GraphDefinition = _reflection.GeneratedProtocolMessageType('GraphDefinition', (_message.Message,), {

  'NodesEntry' : _reflection.GeneratedProtocolMessageType('NodesEntry', (_message.Message,), {
    'DESCRIPTOR' : _GRAPHDEFINITION_NODESENTRY,
    '__module__' : 'GrpcGraphEvaluator_pb2'
    # @@protoc_insertion_point(class_scope:GrpcGraphEvaluator.GraphDefinition.NodesEntry)
    })
  ,
  'DESCRIPTOR' : _GRAPHDEFINITION,
  '__module__' : 'GrpcGraphEvaluator_pb2'
  # @@protoc_insertion_point(class_scope:GrpcGraphEvaluator.GraphDefinition)
  })
_sym_db.RegisterMessage(GraphDefinition)
_sym_db.RegisterMessage(GraphDefinition.NodesEntry)

InputRequest = _reflection.GeneratedProtocolMessageType('InputRequest', (_message.Message,), {
  'DESCRIPTOR' : _INPUTREQUEST,
  '__module__' : 'GrpcGraphEvaluator_pb2'
  # @@protoc_insertion_point(class_scope:GrpcGraphEvaluator.InputRequest)
  })
_sym_db.RegisterMessage(InputRequest)

OutputRequest = _reflection.GeneratedProtocolMessageType('OutputRequest', (_message.Message,), {
  'DESCRIPTOR' : _OUTPUTREQUEST,
  '__module__' : 'GrpcGraphEvaluator_pb2'
  # @@protoc_insertion_point(class_scope:GrpcGraphEvaluator.OutputRequest)
  })
_sym_db.RegisterMessage(OutputRequest)

InputResult = _reflection.GeneratedProtocolMessageType('InputResult', (_message.Message,), {
  'DESCRIPTOR' : _INPUTRESULT,
  '__module__' : 'GrpcGraphEvaluator_pb2'
  # @@protoc_insertion_point(class_scope:GrpcGraphEvaluator.InputResult)
  })
_sym_db.RegisterMessage(InputResult)


DESCRIPTOR._options = None
_GRAPHDEFINITION_NODESENTRY._options = None

_GRAPHEVALUATOR = _descriptor.ServiceDescriptor(
  name='GraphEvaluator',
  full_name='GrpcGraphEvaluator.GraphEvaluator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=923,
  serialized_end=1186,
  methods=[
  _descriptor.MethodDescriptor(
    name='Evaluate',
    full_name='GrpcGraphEvaluator.GraphEvaluator.Evaluate',
    index=0,
    containing_service=None,
    input_type=_GRAPHDEFINITION,
    output_type=_GRAPHEVALUATORMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Input',
    full_name='GrpcGraphEvaluator.GraphEvaluator.Input',
    index=1,
    containing_service=None,
    input_type=_INPUTREQUEST,
    output_type=_INPUTRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Output',
    full_name='GrpcGraphEvaluator.GraphEvaluator.Output',
    index=2,
    containing_service=None,
    input_type=_OUTPUTREQUEST,
    output_type=google_dot_protobuf_dot_any__pb2._ANY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GRAPHEVALUATOR)

DESCRIPTOR.services_by_name['GraphEvaluator'] = _GRAPHEVALUATOR

# @@protoc_insertion_point(module_scope)
